---
- name: backup configuration
  hosts: all
  gather_facts: false
  vars_prompt:
  - name: filebase
    prompt: Enter the filename (base|labX)?
    private: false
  tasks:
  - name: backup {{ inventory_hostname }}
    junipernetworks.junos.junos_config:
      backup: true
      backup_options:
        filename: "{{filebase}}-{{ inventory_hostname }}.txt"
    when: inventory_hostname in groups['juniper']
  - name: backup {{ inventory_hostname }}
    cisco.ios.ios_config:
      backup: true
      backup_options:
        filename: "{{filebase}}-{{ inventory_hostname }}.txt"
    when: inventory_hostname in groups['cisco']
