#!/usr/bin/env ansible-playbook
---
- name: Configure OSPF on r1
  hosts: r1
  gather_facts: false
  tasks:
    - name: Configure OSPF
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 1
              areas:
                - area_id: 0
              network:
                - address: 10.200.200.0
                  wildcard_bits: 0.0.0.255
                  area: 0
                - address: 172.31.1.1
                  wildcard_bits: 0.0.0.0
                  area: 0
      notify: update-startup-config
  handlers:
    - name: update-startup-config
      cisco.ios.ios_command:
        commands:
          - command: copy running-config startup-config
            prompt: 'Destination filename.*'
            answer: 'startup-config'
