#!/usr/bin/env ansible-playbook
---
- name: gather Juniper facts
  hosts: juniper
  gather_facts: false
  tasks:
  - name: Use junos_facts module
    junipernetworks.junos.junos_facts:
  - name: print all junos facts
    ansible.builtin.debug:
      var: ansible_facts
- name: Gather IOS facts
  hosts: cisco
  gather_facts: false
  tasks:
  - name: Use ios_facts module
    cisco.ios.ios_facts:
  - name: print all IOS facts
    ansible.builtin.debug:
      var: ansible_facts
