#!/usr/bin/env ansible-playbook
---
- name: Configure static route on IOS to r2
  hosts: r1
  gather_facts: false
  tasks:
  - name: Set static route on r1 to r2
    cisco.ios.ios_static_routes:
      config:
        - address_families:
          - afi: ipv4
            routes:
            - dest: 172.31.1.2/32
              next_hops:
                - forward_router_address: 10.200.200.2
      state: deleted
    notify: update-startup-config
  handlers:
    - name: update-startup-config
      cisco.ios.ios_command:
        commands:
          - command: copy running-config startup-config
            prompt: 'Destination filename.*'
            answer: 'startup-config'
