---
- name: restore configuration
  hosts: all
  gather_facts: false
  vars_prompt:
  - name: host
    prompt: "Enter the hostname as it appears in the inventory (R1,R2):"
    private: false
  - name: date
    prompt: "Enter the date (YYYY-MM-DD):"
    private: false
  tasks:
  - name: restore {{ inventory_hostname }}
    junipernetworks.junos.junos_config:
        src: "backup/{{ inventory_hostname }}-{{ date }}.txt"
    when: inventory_hostname in groups['juniper'] and inventory_hostname == host
  - name: restore {{ inventory_hostname }}
    cisco.ios.ios_config:
        src: "backup/{{ inventory_hostname }}-{{ date }}.txt"
    when: inventory_hostname in groups['cisco'] and inventory_hostname == host
