#!/usr/bin/env ansible-playbook
---
- name: set hostname configuration
  hosts: r1
  gather_facts: false
  vars:
    hostname: csr-a
  tasks:
  - name: Set system host-name on {{ inventory_hostname }}
    cisco.ios.ios_config:
      lines:
        - hostname {{ hostname }}
      save_when: changed
